plugins {
    alias(nfcLibs.plugins.android.library)
    alias(nfcLibs.plugins.kotlin.android)
}

android {
    namespace = 'eu.pretix.libpretixnfc.android'

    compileSdk = 36

    defaultConfig {
        minSdk = 21
        targetSdk = 36
        multiDexEnabled = true

        vectorDrawables {
            useSupportLibrary = true
        }
    }
    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
    buildFeatures {
        buildConfig = true
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://jitpack.io' }
}

dependencies {
    implementation nfcLibs.kotlin.stdlib
    implementation nfcLibs.core.ktx
    implementation nfcLibs.kotlinx.coroutines.core
    implementation nfcLibs.kotlinx.coroutines.android

    implementation files('libs/acssmc-1.1.8.jar')

    implementation(project(':libpretixnfc')) {
        transitive = true
    }
    implementation(project(':libpretixsync')) {
        transitive = false
    }
    implementation nfcLibs.sentry.android
    implementation nfcLibs.prov
}