pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        maven {
            url = "https://plugins.gradle.org/m2/"
        }
    }
}

plugins {
    id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"
}

dependencyResolutionManagement {
    versionCatalogs {
        nfcCoreLibs {
            from(files('gradle/libs.versions.toml'))
        }
    }
}

rootProject.name = "eu.pretix.libpretixnfc"
